name=MCUW LoRa boards
version=1.0.0
author=MCUW <112967559+mcuw@users.noreply.github.com>
maintainer=MCUW <112967559+mcuw@users.noreply.github.com>
sentence=Arduino library for LoRa boards, including Lilygo ESP32 boards: T-Beam, T3-S3, T3-LoRa32 and more
license=MIT
paragraph=This library provides support for various Lilygo LoRa boards, enabling easy integration and usage of LoRa communication features in Arduino projects.
category=Communication
url=https://github.com/mcuw/LoRaBoards.git
architectures=esp32
