name=MCUW_LoRa_boards
version=0.1.12
author=MCUW <112967559+mcuw@users.noreply.github.com>
maintainer=MCUW <112967559+mcuw@users.noreply.github.com>
sentence=Arduino library for LoRa boards, including Lilygo ESP32 boards: T-Beam, T3-S3, T3-LoRa32 and more
license=MIT
paragraph=This library provides support for various LoRa boards, enabling easy integration and usage of LoRa communication features in Arduino projects.
category=Communication
url=https://github.com/mcuw/LoRaBoards.git
architectures=esp32
depends=RadioLib (>=7.6.0),OneButton (>=2.6.2),XPowersLib (>=0.3.3),ESP8266 and ESP32 OLED driver for SSD1306 displays (>=4.6.2)
includes=LgLoraBoard.h