; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; t-beams
; https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/platformio.ini

[env]
; src_dir = ./examples/lora_send
monitor_speed = 115200
framework = arduino
build_flags =
  -DBOARD_VARIANT_NAME=\"${PIOENV}\"

[esp32_base]
build_flags =
    ${env.build_flags}
; platformio https://github.com/platformio/platform-espressif32/releases
platform = espressif32@6.13.0

[env:ttgo_t_beam_SX1262]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
platform = ${esp32_base.platform}
lib_deps =
  ; XPowersLib - power management series library for ESP32, including PSRAM power management
  lewisxhe/XPowersLib @ ^0.3.3
  ; U8g2 - Arduino Monochrome Graphics Library
  olikraus/U8g2 @ ^2.36.18
  ; RadioLib - SX1262 LoRa library
  jgromes/RadioLib @ ^7.6.0
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = boards_variants
build_flags =
  ${esp32_base.build_flags}
  -DT_BEAM_SX1262
  -mfix-esp32-psram-cache-issue
  -DBOARD_HAS_PSRAM

