; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; LilyGo LoRa boards platformio.ini
; https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/platformio.ini

[platformio]
; uncomment to build an example
; src_dir = ./examples/blink
; src_dir = ./examples/button
; src_dir = ./examples/l9110_motor
; src_dir = ./examples/lora_sender
; src_dir = ./examples/lora_receiver
; src_dir = ./examples/scan_i2c_addresses

[env]
monitor_speed = 115200
framework = arduino
build_flags =
  -D BOARD_VARIANT_NAME=\"${PIOENV}\"
  ; debug level: 5=VERBOSE, 4=DEBUG https://docs.platformio.org/en/latest/platforms/espressif32.html#debug-level
  ;  -DCORE_DEBUG_LEVEL=5
lib_deps =
  src/
  ; RadioLib - LoRa library
  ; releases https://github.com/jgromes/RadioLib/releases
  jgromes/RadioLib @ ^7.6.0
  ; button handling library, used e.g. in TTGO T-Beam
  mathertel/OneButton @ ^2.6.2
  ; XPowersLib - power management series library for ESP32, including PSRAM power management
  lewisxhe/XPowersLib @ ^0.3.3
  ; OLED driver for SSD1306 displays, used e.g. in TTGO Lora32 v1.6.1
  thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.6.2

; CUSTOM options
; You need manually inject these options into a section
; using ${extra.<name_of_option>} (see below)
[extra]
; https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html
; optional flags only needed for base esp32 boards
; specific boards or boards under the /boards directory are already configured with psram support
build_flags_psram =
    -D BOARD_HAS_PSRAM=1
    -mfix-esp32-psram-cache-issue ; https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html#esp32-rev-v1

[esp32_base]
build_flags =
    ${env.build_flags}
; use pioarduino, versions: https://github.com/pioarduino/platform-espressif32/releases
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
; or use platformio, versions: https://github.com/platformio/platform-espressif32/releases
; platform = espressif32@6.13.0
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
lib_deps =
    ${env.lib_deps}

[env:ttgo_t_beam_v0_7]
extends = esp32_base
board = ttgo-t-beam
build_flags =
  ${esp32_base.build_flags}
  ${extra.build_flags_psram} ; 8MB PSRAM
  -D HAS_BUTTON
  -D HAS_LED
  ; -D HAS_GPS
  -D USE_SX1276
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = variants
lib_deps =
  ${esp32_base.lib_deps}

[env:ttgo_t_beam_v1_1]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
extends = esp32_base
board = esp32dev
platform = ${esp32_base.platform}
lib_deps =
  ${esp32_base.lib_deps}
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = variants
build_flags =
  ${esp32_base.build_flags}
  ${extra.build_flags_psram} ; 8MB PSRAM
  -D HAS_BUTTON
  -D HAS_PMU
  ; -D HAS_GPS
  -D USE_SX1262

; https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/docs/en/t3_v161_sx1276/t3_v161_sx1276_hw.md
; pio board config: https://docs.platformio.org/en/latest/boards/espressif32/ttgo-lora32-v1.html
[env:ttgo_lora32_v1_6_1]
extends = esp32_base
board = ttgo-lora32-v1
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = variants
build_flags =
  ${esp32_base.build_flags}
  -D HAS_DISPLAY_SSD1306
  -D HAS_LED
  ; -D HIDE_SPLASH_SCREEN
  -D USE_SX1276
lib_deps =
  ${esp32_base.lib_deps}