; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; t-beams
; https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/platformio.ini

[platformio]
; src_dir = ./examples/blink
; src_dir = ./examples/button
; src_dir = ./examples/l9110_motor
; src_dir = ./examples/lora_sender
; src_dir = ./examples/lora_receiver
; src_dir = ./examples/scan_i2c_addresses

[env]
monitor_speed = 115200
framework = arduino
build_flags =
  -D BOARD_VARIANT_NAME=\"${PIOENV}\"
  -D CORE_DEBUG_LEVEL=4
lib_deps =
  ; RadioLib - SX1262 LoRa library
  ; releases https://github.com/jgromes/RadioLib/releases
  jgromes/RadioLib @ ^7.6.0
  ; LoRa - TTGO Lora chip can be used for v0.7 instead off RadioLib
  ; sandeepmistry/LoRa @ ^0.8.0
  mathertel/OneButton @ ^2.6.2
  ; XPowersLib - power management series library for ESP32, including PSRAM power management
  lewisxhe/XPowersLib @ ^0.3.3
  ; U8g2 - Arduino Monochrome Graphics Library
  olikraus/U8g2 @ ^2.36.18
  thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.6.2

[esp32_base]
build_flags =
    ${env.build_flags}
; platformio https://github.com/platformio/platform-espressif32/releases
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
platform = espressif32@6.13.0
lib_deps =
    ${env.lib_deps}

[env:ttgo_t_beam_v0_7]
extends = esp32_base
board = ttgo-t-beam
build_flags =
  ${esp32_base.build_flags}
  -mfix-esp32-psram-cache-issue
  -D BOARD_HAS_PSRAM
  -D HAS_BUTTON
  -D HAS_LED
  ; -D HAS_GPS
  -D USE_SX1276
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = boards_variants
lib_deps =
  ${esp32_base.lib_deps}

[env:ttgo_t_beam_v1_1]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
extends = esp32_base
board = esp32dev
platform = ${esp32_base.platform}
lib_deps =
  ${esp32_base.lib_deps}
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = boards_variants
build_flags =
  ${esp32_base.build_flags}
  -mfix-esp32-psram-cache-issue
  -D BOARD_HAS_PSRAM
  -D HAS_BUTTON
  -D HAS_PMU
  ; -D HAS_GPS
  -D USE_SX1262

; https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/docs/en/t3_v161_sx1276/t3_v161_sx1276_hw.md
; pio board config: https://docs.platformio.org/en/latest/boards/espressif32/ttgo-lora32-v1.html
[env:ttgo_lora32_v1_6_1]
extends = esp32_base
board = ttgo-lora32-v1
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = boards_variants
build_flags =
  ${esp32_base.build_flags}
  -D HAS_DISPLAY_SSD1306
  -D HAS_LED
  ; -D HIDE_SPLASH_SCREEN
  -D USE_SX1276

lib_deps =
  ${esp32_base.lib_deps}